from types import TracebackType
from typing import Any, Dict, Iterator, List, Mapping, Optional, Sequence, Type, TypedDict, Union

Json = Union[None, bool, int, float, str, List["Json"], Dict[str, "Json"]]

class EventRow(TypedDict, total=False):
    offset: int
    timestamp_ms: int
    body: Json
    event_type: str
    schema_version: int
    metadata: Dict[str, bytes]
    stream_revision: int
    branch_id: str
    namespace: Optional[str]

class ReplayPage(TypedDict):
    records: List[EventRow]
    continuation: int
    done: bool

class SalamanderError(RuntimeError): ...
class InvalidArgumentError(ValueError): ...
class ConflictError(ValueError): ...
class NotFoundError(KeyError): ...
class LockedError(OSError): ...
class IoError(OSError): ...
class CorruptionError(RuntimeError): ...
class UnsupportedFormatError(RuntimeError): ...
class CodecError(ValueError): ...
class ResourceLimitError(ValueError): ...
class CancelledError(RuntimeError): ...

class Reader:
    def next_page(self) -> ReplayPage: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

class Watch(Iterator[EventRow]):
    def __iter__(self) -> Watch: ...
    def __next__(self) -> EventRow: ...
    def ack(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Watch: ...
    def __exit__(self, exc_type: Optional[Type[BaseException]], exc_value: Optional[BaseException], traceback: Optional[TracebackType]) -> bool: ...

class View:
    def get(self, key: str) -> Optional[Json]: ...
    def by(self, index: str, key: Json) -> List[Json]: ...
    def range(self, lo: str, hi: str) -> List[Json]: ...
    def prefix(self, prefix: str) -> List[Json]: ...
    def len(self) -> int: ...

class Salamander:
    @staticmethod
    def open(path: str, commit_every_bytes: Optional[int] = ..., commit_every_count: Optional[int] = ..., commit_every_millis: Optional[int] = ..., snapshot_every_events: Optional[int] = ..., snapshot_every_bytes: Optional[int] = ..., snapshot_every_millis: Optional[int] = ...) -> Salamander: ...
    def __enter__(self) -> Salamander: ...
    def __exit__(self, exc_type: Optional[Type[BaseException]], exc_value: Optional[BaseException], traceback: Optional[TracebackType]) -> bool: ...
    def close(self) -> None: ...
    def append(self, namespace: str, event: Json) -> int: ...
    def append_receipt(self, namespace: str, event: Json) -> Dict[str, Any]: ...
    def append_batch(self, namespace: str, events: Sequence[Mapping[str, Any]], *, branch: Optional[str] = ..., expected_revision: Optional[Union[str, int]] = ..., idempotency_key: Optional[Union[str, bytes]] = ..., durability: str = ...) -> Dict[str, Any]: ...
    def append_branch(self, branch: str, namespace: str, event: Json) -> int: ...
    def commit(self) -> int: ...
    def head(self) -> int: ...
    def durable_head(self) -> int: ...
    def uncommitted_count(self) -> int: ...
    def replay(self, namespace: str, start: int = ..., end: Optional[int] = ...) -> List[EventRow]: ...
    def open_reader(self, namespace: str, start: int = ..., end: Optional[int] = ..., page_events: int = ..., page_bytes: int = ...) -> Reader: ...
    def register_view(self, name: str, key: str, indexes: Optional[Mapping[str, str]] = ..., where_field: Optional[str] = ..., where_value: Json = ...) -> None: ...
    def deregister_view(self, name: str) -> bool: ...
    def view(self, name: str) -> View: ...
    def fork(self, namespace: str, at: int, parent: Optional[str] = ...) -> str: ...
    def watch(self, namespace: Optional[str] = ..., branch: Optional[str] = ..., start: Optional[int] = ..., consumer_id: Optional[str] = ..., timeout: Optional[float] = ..., page_batches: int = ..., page_bytes: int = ...) -> Watch: ...
    def diff(self, left: str, right: str, namespace: Optional[str] = ..., left_until: Optional[int] = ..., right_until: Optional[int] = ..., page_events: int = ..., page_bytes: int = ...) -> Dict[str, Any]: ...
    def history(self, namespace: str) -> List[EventRow]: ...
    def branch_history(self, branch: str, namespace: str) -> List[EventRow]: ...
    def branch_ancestry(self, branch: str) -> List[Dict[str, Any]]: ...
    def archive_branch(self, branch: str) -> Dict[str, Any]: ...
    def create_snapshot(self, projection: str) -> Dict[str, Any]: ...
    def list_snapshots(self, projection: str) -> List[Dict[str, Any]]: ...
    def verify_snapshot(self, snapshot_id: str) -> Dict[str, Any]: ...
    def delete_snapshot(self, snapshot_id: str) -> bool: ...
    def delete_all_derived_state(self) -> None: ...
    def rebuild_projection(self, projection: str) -> None: ...

def open(path: str, commit_every_bytes: Optional[int] = ..., commit_every_count: Optional[int] = ..., commit_every_millis: Optional[int] = ..., snapshot_every_events: Optional[int] = ..., snapshot_every_bytes: Optional[int] = ..., snapshot_every_millis: Optional[int] = ...) -> Salamander: ...

__version__: str
