from types import TracebackType
from typing import Any, Dict, Iterator, List, Mapping, Optional, Sequence, Type, TypedDict, Union

Json = Union[None, bool, int, float, str, List["Json"], Dict[str, "Json"]]

class EventRow(TypedDict, total=False):
    offset: int
    timestamp_ms: int
    body: Json
    event_type: str
    schema_version: int
    metadata: Dict[str, bytes]
    stream_revision: int
    branch_id: str
    namespace: Optional[str]

class ReplayPage(TypedDict):
    records: List[EventRow]
    continuation: int
    done: bool

class FeedBootstrap(TypedDict):
    database_id: str
    generation: int
    floor: int
    consumer_id: str
    checkpoint_id: str
    branches: List[str]
    streams: List[str]
    event_types: List[str]
    byte_length: int
    checksum: int
    resume_from: int
    codec: str
    codec_version: int

class RetentionStatus(TypedDict):
    database_id: str
    generation: int
    floor: int
    durable_head: int
    requested_floor: int
    effective_floor: int
    anchor_ready: bool
    reclaimable_bytes: int
    reclaimable_segments: List[Dict[str, int]]
    blockers: List[Dict[str, Any]]
    open_readers: int
    open_feeds: int
    consumers: List[Dict[str, Any]]
    cleanup: Dict[str, Any]

class RetentionPolicyPreview(TypedDict):
    policy: str
    value: int
    selected_floor: int
    target_satisfied: bool
    explanation: str
    plan: Dict[str, Any]

class SalamanderError(RuntimeError): ...
class InvalidArgumentError(ValueError): ...
class ConflictError(ValueError): ...
class NotFoundError(KeyError): ...
class LockedError(OSError): ...
class IoError(OSError): ...
class CorruptionError(RuntimeError): ...
class UnsupportedFormatError(RuntimeError): ...
class CodecError(ValueError): ...
class ResourceLimitError(ValueError): ...
class CancelledError(RuntimeError): ...
class PositionUnavailableError(ValueError):
    bootstrap: Optional[FeedBootstrap]

class Reader:
    def next_page(self) -> ReplayPage: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

class Watch(Iterator[EventRow]):
    def __iter__(self) -> Watch: ...
    def __next__(self) -> EventRow: ...
    def ack(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Watch: ...
    def __exit__(self, exc_type: Optional[Type[BaseException]], exc_value: Optional[BaseException], traceback: Optional[TracebackType]) -> bool: ...

class View:
    def get(self, key: str) -> Optional[Json]: ...
    def by(self, index: str, key: Json) -> List[Json]: ...
    def range(self, lo: str, hi: str) -> List[Json]: ...
    def prefix(self, prefix: str) -> List[Json]: ...
    def len(self) -> int: ...

class Salamander:
    @staticmethod
    def open(path: str, commit_every_bytes: Optional[int] = ..., commit_every_count: Optional[int] = ..., commit_every_millis: Optional[int] = ..., snapshot_every_events: Optional[int] = ..., snapshot_every_bytes: Optional[int] = ..., snapshot_every_millis: Optional[int] = ...) -> Salamander: ...
    def __enter__(self) -> Salamander: ...
    def __exit__(self, exc_type: Optional[Type[BaseException]], exc_value: Optional[BaseException], traceback: Optional[TracebackType]) -> bool: ...
    def close(self) -> None: ...
    def append(self, namespace: str, event: Json) -> int: ...
    def append_receipt(self, namespace: str, event: Json) -> Dict[str, Any]: ...
    def append_batch(self, namespace: str, events: Sequence[Mapping[str, Any]], *, branch: Optional[str] = ..., expected_revision: Optional[Union[str, int]] = ..., idempotency_key: Optional[Union[str, bytes]] = ..., durability: str = ...) -> Dict[str, Any]: ...
    def append_branch(self, branch: str, namespace: str, event: Json) -> int: ...
    def commit(self) -> int: ...
    def head(self) -> int: ...
    def durable_head(self) -> int: ...
    def retention_floor(self) -> int: ...
    def retention_status(self, keep_from: Optional[int] = ...) -> RetentionStatus: ...
    def plan_retention(self, keep_from: int) -> Dict[str, Any]: ...
    def plan_retention_policy(self, policy: str, value: int) -> RetentionPolicyPreview: ...
    def create_retention_anchor(self, keep_from: int) -> Dict[str, Any]: ...
    def apply_retention(self, plan_id: str) -> Dict[str, int]: ...
    def register_branch_bootstrap(
        self, branch: str, keep_from: int, checkpoint: bytes
    ) -> int: ...
    def register_consumer_bootstrap(
        self, consumer_id: str, keep_from: int, checkpoint: bytes
    ) -> int: ...
    def register_feed_bootstrap(
        self,
        consumer_id: str,
        keep_from: int,
        checkpoint: bytes,
        branch: Optional[str] = ...,
        codec: str = ...,
        codec_version: int = ...,
    ) -> int: ...
    def fetch_feed_bootstrap(
        self, descriptor: FeedBootstrap, maximum_bytes: int
    ) -> bytes: ...
    def resume_watch(
        self,
        descriptor: FeedBootstrap,
        namespace: Optional[str] = ...,
        timeout: Optional[float] = ...,
        page_batches: int = ...,
        page_bytes: int = ...,
    ) -> Watch: ...
    def branch_bootstrap(self, branch: str) -> Optional[bytes]: ...
    def consumer_bootstrap(self, consumer_id: str) -> Optional[bytes]: ...
    def uncommitted_count(self) -> int: ...
    def replay(self, namespace: str, start: int = ..., end: Optional[int] = ...) -> List[EventRow]: ...
    def open_reader(self, namespace: str, start: int = ..., end: Optional[int] = ..., page_events: int = ..., page_bytes: int = ...) -> Reader: ...
    def register_view(self, name: str, key: str, indexes: Optional[Mapping[str, str]] = ..., where_field: Optional[str] = ..., where_value: Json = ...) -> None: ...
    def deregister_view(self, name: str) -> bool: ...
    def view(self, name: str) -> View: ...
    def fork(self, namespace: str, at: int, parent: Optional[str] = ...) -> str: ...
    def watch(self, namespace: Optional[str] = ..., branch: Optional[str] = ..., start: Optional[int] = ..., consumer_id: Optional[str] = ..., timeout: Optional[float] = ..., page_batches: int = ..., page_bytes: int = ...) -> Watch: ...
    def diff(self, left: str, right: str, namespace: Optional[str] = ..., left_until: Optional[int] = ..., right_until: Optional[int] = ..., page_events: int = ..., page_bytes: int = ...) -> Dict[str, Any]: ...
    def history(self, namespace: str) -> List[EventRow]: ...
    def branch_history(self, branch: str, namespace: str) -> List[EventRow]: ...
    def branch_ancestry(self, branch: str) -> List[Dict[str, Any]]: ...
    def archive_branch(self, branch: str) -> Dict[str, Any]: ...
    def create_snapshot(self, projection: str) -> Dict[str, Any]: ...
    def list_snapshots(self, projection: str) -> List[Dict[str, Any]]: ...
    def verify_snapshot(self, snapshot_id: str) -> Dict[str, Any]: ...
    def delete_snapshot(self, snapshot_id: str) -> bool: ...
    def delete_all_derived_state(self) -> None: ...
    def rebuild_projection(self, projection: str) -> None: ...

def open(path: str, commit_every_bytes: Optional[int] = ..., commit_every_count: Optional[int] = ..., commit_every_millis: Optional[int] = ..., snapshot_every_events: Optional[int] = ..., snapshot_every_bytes: Optional[int] = ..., snapshot_every_millis: Optional[int] = ...) -> Salamander: ...

__version__: str
